version: "3"
services:
  db:
    image: zhunism/todo_app_database:v1.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todo_db
    restart: on-failure

  backend:
    depends_on:
      - db
    image: zhunism/todo_app_backend:v1.0
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      JWT_SECRET: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      ORIGIN_FRONTEND: http://localhost:3000

  frontend:
    depends_on:
      - backend
    image: zhunism/todo_app_frontend:v1.0
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      API_URL: http://localhost:8081/api
    
